spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: "123456"
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/vpac_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8


base:
  boot.async-init.jpa.enabled: true
  common.cache:
    enabled: true
    impl: local  #缓存实现：local(默认值Caffeine)、redis
  host:
    api: "http://127.0.0.1:60606"

  #报警通知，暂只支持钉钉群
  notify:
    dingtalk:
      test: true
      enabled: true
  wechat:
    miniapp:
      name: "视力防控平台"
      appid: wx54a25525a1b0b301
      secret: "xxx"
      token: 111
      aesKey: 111
      msgDataFormat: JSON

  oss:
    #OSS服务实现： local、ali、qiniu
    impl: "local"
    ali:
      accessKeyId: "xxx"
      accessKeySecret: "xxx"
      endpoint: 'https://oss-cn-hangzhou.aliyuncs.com'
      bucketUrl: 'https://vpac-prod.oss-cn-hangzhou.aliyuncs.com'
      bucket: 'vpac-prod'
      fileSizeByte: '52428800' #50m
      tokenExpireSeconds: '1800'
      viewImage: false
      resize:
        max-width: 1920
      # 验签公钥 https://gosspublic.alicdn.com/callback_pub_key_v1.pem
      callbackPubKey: |
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKs/JBGzwUB2aVht4crBx3oIPBLNsjGs
        C0fTXv+nvlmklvkcolvpvXLTjaxUHR3W9LXxQ2EHXAJfCB+6H2YF1k8CAwEAAQ==

  admin:
    info:
      system-name: "XXX后台管理系统"
      copyright: "Copyright © <a target='_blank' href='https://www.baidu.com'>XXX后台管理系统</a>"
      login-title: "<label style='font-size:25px;margin-top:12px;color:#555'>{systemName}</label>"
#      login-title: "<img style='height:60px;float:left' src='/admin/img/logo.png' onerror='this.remove()'/><label style='font-size:25px;margin-top:12px;color:#555'>{systemName}</label>"

